### ISSUE TITLE
Evaluate rule after a given time

### ISSUE THREAD

**Issue by mitze** [hoaproject/Ruler#75]
Hello again.

Another question / proposal:

I'm trying to solve how to assess a rule with a timing condition (Eg value > 21 and elapsed_time > 300)

When the other conditions are true, after 300 seconds I want to check if the context remain the same. It's easy search in de DB to find the received values in the time range, but I don't know how to postpone the evaluation without blocking the whole process.

I saw that the Worker library could serve my purpose, but it seems this is overengineering.

Is there any way to do what I need with Ruler?

Any clue would be greatly appreciated.

Thanks in advance.

**Comment by Hywan** [comment]
Hello :-),

I reckon this is not part of `Hoa\Ruler` to address your issue. Since PHP has no native asynchronous mechanism, yes, you will have to block the main thread in order to wait 300 seconds. You maybe can schedule a task somewhere to continue your check. Yes, `Hoa\Worker` could be a good tool for that :-).

**Comment by mitze** [comment]
Thank you. I'll try that way.
